export type OsintSource = {
  id: string;
  category: string;
  title: string;
  description: string;
  url: string;
  searchUrl?: (query: string) => string;
};

export const OSINT_BRAZUCA_META = {
  title: 'OSINT-Brazuca',
  origin: 'https://github.com/UnkL4b/OSINT-Brazuca',
  license: 'MIT',
  authors: ['Cleiton P. (MrCl0wnLab)', 'Diego (c4nh0t0)'],
} as const;

const g = (q: string) => `https://www.google.com/search?q=${encodeURIComponent(q)}`;
const jb = (q: string) => `https://www.jusbrasil.com.br/busca?q=${encodeURIComponent(q)}`;
const esc = (q: string) => `https://www.escavador.com/busca?q=${encodeURIComponent(q)}`;

export const OSINT_SOURCES: OsintSource[] = [
  {
    id: 'bolsa-familia',
    category: 'Benefícios sociais',
    title: 'Consulta Benefícios Sociais (Bolsa Família)',
    description: 'Consulta pública de benefícios sociais da Caixa.',
    url: 'https://www.beneficiossociais.caixa.gov.br/consulta/beneficio/04.01.00-00_00.asp',
  },
  {
    id: 'auxilio-emergencial',
    category: 'Benefícios sociais',
    title: 'Consulta ao Auxílio Emergencial',
    description: 'Resultado da análise de elegibilidade do Auxílio Emergencial.',
    url: 'https://consultaauxilio.cidadania.gov.br/consulta/#/',
  },
  {
    id: 'cnpj-receita',
    category: 'Benefícios sociais',
    title: 'Comprovante Situação Cadastral PJ (Receita)',
    description: 'Comprovante de inscrição e situação cadastral de pessoa jurídica.',
    url: 'http://www.receita.fazenda.gov.br/PessoaJuridica/CNPJ/cnpjreva/Cnpjreva_Solicitacao.asp',
  },
  {
    id: 'esaj-tjac',
    category: 'Consulta de processos',
    title: 'Portal e-SAJ TJAC',
    description: 'Consulta processual do Tribunal de Justiça do Acre.',
    url: 'https://esaj.tjac.jus.br/esaj/portal.do?servico=190090#',
    searchUrl: (q) => g(`site:esaj.tjac.jus.br ${q}`),
  },
  {
    id: 'esaj-tjba',
    category: 'Consulta de processos',
    title: 'Portal e-SAJ TJBA',
    description: 'Consulta processual do Tribunal de Justiça da Bahia.',
    url: 'https://esaj.tjba.jus.br/esaj/portal.do?servico=190090#',
    searchUrl: (q) => g(`site:esaj.tjba.jus.br ${q}`),
  },
  {
    id: 'esaj-tjce',
    category: 'Consulta de processos',
    title: 'Portal e-SAJ TJCE',
    description: 'Consulta processual do Tribunal de Justiça do Ceará.',
    url: 'https://esaj.tjce.jus.br/esaj/portal.do?servico=190090#',
    searchUrl: (q) => g(`site:esaj.tjce.jus.br ${q}`),
  },
  {
    id: 'esaj-tjsc',
    category: 'Consulta de processos',
    title: 'Portal e-SAJ TJSC',
    description: 'Consulta processual do Tribunal de Justiça de Santa Catarina.',
    url: 'https://esaj.tjsc.jus.br/esaj/portal.do?servico=190090#',
    searchUrl: (q) => g(`site:esaj.tjsc.jus.br ${q}`),
  },
  {
    id: 'esaj-tjsp',
    category: 'Consulta de processos',
    title: 'Portal e-SAJ TJSP',
    description: 'Consulta processual do Tribunal de Justiça de São Paulo.',
    url: 'https://esaj.tjsp.jus.br/esaj/portal.do?servico=190090#',
    searchUrl: (q) => g(`site:esaj.tjsp.jus.br ${q}`),
  },
  {
    id: 'esaj-tjam',
    category: 'Consulta de processos',
    title: 'Portal e-SAJ TJAM',
    description: 'Consulta processual do Tribunal de Justiça do Amazonas.',
    url: 'http://esaj.tjam.jus.br/esaj/portal.do?servico=190090#',
    searchUrl: (q) => g(`site:esaj.tjam.jus.br ${q}`),
  },
  {
    id: 'trf1',
    category: 'Consulta de processos',
    title: 'TRF1',
    description: 'Tribunal Regional Federal da 1ª Região (DF e 13 estados).',
    url: 'https://portal.trf1.jus.br',
    searchUrl: (q) => g(`site:trf1.jus.br ${q}`),
  },
  {
    id: 'trf2',
    category: 'Consulta de processos',
    title: 'TRF2',
    description: 'Justiça Federal da 2ª Região (RJ e ES).',
    url: 'https://portal.trf2.jus.br',
    searchUrl: (q) => g(`site:trf2.jus.br ${q}`),
  },
  {
    id: 'trf5',
    category: 'Consulta de processos',
    title: 'TRF5',
    description: 'TRF5 (AL, CE, PB, PE, RN, SE).',
    url: 'https://portal.trf5.jus.br',
    searchUrl: (q) => g(`site:trf5.jus.br ${q}`),
  },
  {
    id: 'jusbrasil',
    category: 'Consulta de processos',
    title: 'JusBrasil',
    description: 'Processos, jurisprudência e menções jurídicas públicas.',
    url: 'https://www.jusbrasil.com.br/',
    searchUrl: jb,
  },
  {
    id: 'escavador',
    category: 'Consulta de processos',
    title: 'Escavador',
    description: 'Pessoas, instituições e processos judiciais em fontes públicas.',
    url: 'https://www.escavador.com/',
    searchUrl: esc,
  },
  {
    id: 'cnpj-reva',
    category: 'CPF / CNPJ',
    title: 'Receita Federal — CNPJ',
    description: 'Consulta oficial de CNPJ na Receita Federal.',
    url: 'http://servicos.receita.fazenda.gov.br/Servicos/cnpjreva/Cnpjreva_Solicitacao.asp',
  },
  {
    id: 'brasilcnpj',
    category: 'CPF / CNPJ',
    title: 'Brasil CNPJ',
    description: 'Consulta de dados cadastrais de empresas.',
    url: 'https://brasilcnpj.net/',
    searchUrl: (q) => `https://brasilcnpj.net/?s=${encodeURIComponent(q)}`,
  },
  {
    id: 'cnpj-biz',
    category: 'CPF / CNPJ',
    title: 'CNPJ.biz',
    description: 'Busca de empresas por CNPJ ou razão social.',
    url: 'https://cnpj.biz/',
    searchUrl: (q) => g(`site:cnpj.biz ${q}`),
  },
  {
    id: 'cadastro-empresa',
    category: 'CPF / CNPJ',
    title: 'Cadastro Empresa',
    description: 'Informações cadastrais de pessoas jurídicas.',
    url: 'https://cadastroempresa.com.br/',
    searchUrl: (q) => g(`site:cadastroempresa.com.br ${q}`),
  },
  {
    id: 'casa-dos-dados',
    category: 'CPF / CNPJ',
    title: 'Casa dos Dados',
    description: 'Busca de empresas e sócios em bases públicas.',
    url: 'https://casadosdados.com.br/',
    searchUrl: (q) => `https://casadosdados.com.br/solucao/cnpj?q=${encodeURIComponent(q)}`,
  },
  {
    id: 'cnpjs-rocks',
    category: 'CPF / CNPJ',
    title: 'CNPJs.rocks',
    description: 'Consulta rápida de CNPJ.',
    url: 'https://cnpjs.rocks/',
    searchUrl: (q) => g(`site:cnpjs.rocks ${q}`),
  },
  {
    id: 'informe-cadastral',
    category: 'CPF / CNPJ',
    title: 'Informe Cadastral',
    description: 'Situação cadastral de empresas.',
    url: 'https://www.informecadastral.com.br/',
    searchUrl: (q) => g(`site:informecadastral.com.br ${q}`),
  },
  {
    id: 'situacao-cadastral-info',
    category: 'CPF / CNPJ',
    title: 'SituacaoCadastral.info',
    description: 'Consulta de situação cadastral.',
    url: 'https://www.situacaocadastral.info/',
  },
  {
    id: 'simples-nacional',
    category: 'CPF / CNPJ',
    title: 'Simples Nacional',
    description: 'Consulta ao Simples Nacional da Receita.',
    url: 'http://www8.receita.fazenda.gov.br/simplesnacional/aplicacoes.aspx?id=21',
  },
  {
    id: 'situacao-cadastral',
    category: 'CPF / CNPJ',
    title: 'Situação Cadastral CPF/CNPJ',
    description: 'Confirma nome e situação cadastral de CPF e CNPJ.',
    url: 'https://www.situacao-cadastral.com/',
  },
  {
    id: 'imei',
    category: 'Telecom',
    title: 'Consulta Serial / IMEI',
    description: 'Legalidade do aparelho via serial/IMEI.',
    url: 'https://www.consultaserialaparelho.com.br/public-web/homeSiga',
  },
  {
    id: 'abr-telecom',
    category: 'Telecom',
    title: 'ABR Telecom — Situação da linha',
    description: 'Consulta de situação atual da linha via operadora.',
    url: 'https://consultanumero.abrtelecom.com.br/consultanumero/consulta/consultaSituacaoAtualCtg',
  },
  {
    id: 'consulta-numero',
    category: 'Telecom',
    title: 'Consulta Número',
    description: 'Operadora a partir do número celular.',
    url: 'https://consultanumero.info/',
  },
  {
    id: 'qual-operadora',
    category: 'Telecom',
    title: 'Qual Operadora',
    description: 'Identifica operadora do número informado.',
    url: 'https://www.qualoperadora.net/',
  },
  {
    id: 'consulta-operadora',
    category: 'Telecom',
    title: 'Consulta Operadora',
    description: 'Consulta de operadora por telefone.',
    url: 'http://consultaoperadora.com.br/site2015/',
  },
  {
    id: 'cadastro-pre',
    category: 'Telecom',
    title: 'Cadastro Pré (linha pré ativa)',
    description: 'Consulta de linha pré-paga ativa (Algar, Claro, Oi, Sercomtel, TIM, Vivo).',
    url: 'https://cadastropre.com.br/#/consulta',
  },
  {
    id: 'teleco-erb',
    category: 'ERBs / antenas',
    title: 'Teleco ERB',
    description: 'Estações rádio base e cobertura celular.',
    url: 'https://www.teleco.com.br/erb.asp',
  },
  {
    id: 'anatel-estacoes',
    category: 'ERBs / antenas',
    title: 'Anatel — Estações por localidade',
    description: 'Lista de estações licenciadas por localidade.',
    url: 'https://sistemas.anatel.gov.br/stel/consultas/ListaEstacoesLocalidade/tela.asp?pNumServico=010',
  },
  {
    id: 'mapa-erb',
    category: 'ERBs / antenas',
    title: 'Mapa ERB Telebrasil',
    description: 'Mapa de estações rádio base.',
    url: 'http://www.telecocare.com.br/telebrasil/mapa_erb.php',
  },
  {
    id: 'anatel-licenciamento',
    category: 'ERBs / antenas',
    title: 'Anatel — Licenciamento',
    description: 'Consulta pública de licenciamento de estações.',
    url: 'http://sistemas.anatel.gov.br/se/public/view/b/licenciamento.php',
  },
  {
    id: 'anatel-movel',
    category: 'ERBs / antenas',
    title: 'Anatel — Serviço Móvel',
    description: 'Sistema de serviço móvel da Anatel.',
    url: 'http://sistemas.anatel.gov.br/siec-servico-movel-web/',
  },
  {
    id: 'dados-erb',
    category: 'ERBs / antenas',
    title: 'Dados.gov — ERB',
    description: 'Datasets públicos de estações rádio base.',
    url: 'https://dados.gov.br/dataset?tags=ERB',
  },
  {
    id: 'cobertura-celular',
    category: 'ERBs / antenas',
    title: 'Cobertura Celular',
    description: 'Mapas de cobertura das operadoras.',
    url: 'http://www.coberturacelular.com.br/',
  },
  {
    id: 'lattes',
    category: 'Informações acadêmicas',
    title: 'Currículo Lattes / CNPq',
    description: 'Busca textual de currículos acadêmicos.',
    url: 'https://buscatextual.cnpq.br/buscatextual/busca.do?metodo=apresentar',
    searchUrl: (q) => g(`site:buscatextual.cnpq.br ${q}`),
  },
  {
    id: 'inpe-mapsat',
    category: 'Mapas e geo',
    title: 'INPE MapSat',
    description: 'Imagens de satélite do INPE.',
    url: 'http://satelite.cptec.inpe.br/mapsat/',
  },
  {
    id: 'inpe-sos-chuva',
    category: 'Mapas e geo',
    title: 'INPE SOS Chuva',
    description: 'Monitoramento de precipitação.',
    url: 'http://sigma-soschuva.cptec.inpe.br/#',
  },
  {
    id: 'inpe-queimadas',
    category: 'Mapas e geo',
    title: 'INPE Queimadas',
    description: 'Banco de dados de queimadas.',
    url: 'https://queimadas.dgi.inpe.br/queimadas/bdqueimadas',
  },
  {
    id: 'iphan',
    category: 'Mapas e geo',
    title: 'IPHAN SICG',
    description: 'Patrimônio cultural brasileiro.',
    url: 'https://sicg.iphan.gov.br/sicg/pesquisarBem',
    searchUrl: (q) => g(`site:sicg.iphan.gov.br ${q}`),
  },
  {
    id: 'fns',
    category: 'Saúde',
    title: 'Fundo Nacional de Saúde',
    description: 'Consulta consolidada do FNS.',
    url: 'https://consultafns.saude.gov.br/#/consolidada',
  },
  {
    id: 'linkedin-br',
    category: 'Redes sociais',
    title: 'LinkedIn Brasil',
    description: 'Perfis profissionais e vagas no Brasil.',
    url: 'https://www.linkedin.com/',
    searchUrl: (q) => `https://www.linkedin.com/search/results/all/?keywords=${encodeURIComponent(q)}`,
  },
  {
    id: 'twitter-pt',
    category: 'Redes sociais',
    title: 'X / Twitter (pt)',
    description: 'Busca avançada em português.',
    url: 'https://twitter.com/search-advanced',
    searchUrl: (q) => `https://twitter.com/search?q=${encodeURIComponent(`${q} lang:pt`)}&src=typed_query`,
  },
  {
    id: 'facebook',
    category: 'Redes sociais',
    title: 'Facebook',
    description: 'Menções públicas no Facebook via Google.',
    url: 'https://www.facebook.com/',
    searchUrl: (q) => g(`site:facebook.com "${q}"`),
  },
  {
    id: 'antecedentes',
    category: 'Outras buscas',
    title: 'Antecedentes Criminais (PF)',
    description: 'Certidão de antecedentes da Polícia Federal.',
    url: 'https://servicos.dpf.gov.br/antecedentes-criminais/certidao',
  },
  {
    id: 'falecidos',
    category: 'Outras buscas',
    title: 'Falecidos no Brasil',
    description: 'Busca de óbitos em fontes públicas.',
    url: 'https://www.falecidosnobrasil.org.br/',
    searchUrl: (q) => g(`site:falecidosnobrasil.org.br ${q}`),
  },
  {
    id: 'embarcacoes',
    category: 'Outras buscas',
    title: 'Embarcações Navais',
    description: 'Consulta de embarcações no sistema Mercante.',
    url: 'https://www.mercante.transportes.gov.br/g36127/html/Manife/EmbarcConsul.html?noCampo=cdIrin',
  },
  {
    id: 'registro-civil',
    category: 'Outras buscas',
    title: 'Registro Civil — Transparência',
    description: 'Estatísticas de nascimentos, óbitos, registros e casamentos.',
    url: 'https://transparencia.registrocivil.org.br/registros',
  },
  {
    id: 'whois-br',
    category: 'Outras buscas',
    title: 'WHOIS Registro.br',
    description: 'Informações de domínios .br.',
    url: 'https://registro.br/tecnologia/ferramentas/whois/',
  },
  {
    id: 'procon-sp',
    category: 'Outras buscas',
    title: 'Procon-SP — Evite estes sites',
    description: 'Sites notificados pelo Procon-SP.',
    url: 'https://sistemas.procon.sp.gov.br/evitesite/list/evitesites.php',
  },
  {
    id: 'telenumeros',
    category: 'Outras buscas',
    title: 'Lista Telefônica',
    description: 'Busca em listas telefônicas públicas.',
    url: 'https://www.telenumeros.com/',
    searchUrl: (q) => g(`site:telenumeros.com ${q}`),
  },
  {
    id: 'detran-ma',
    category: 'Outras buscas',
    title: 'DETRAN-MA — Licenciamento',
    description: 'Consulta de licenciamento veicular (Maranhão).',
    url: 'http://licenciamento.detran.ma.gov.br/Licenciamento/consulta/Home.xhtml',
  },
  {
    id: 'inpi',
    category: 'Outras buscas',
    title: 'INPI — Marcas e patentes',
    description: 'Consulta de marcas, patentes e desenhos industriais.',
    url: 'https://busca.inpi.gov.br/pePI/servlet/LoginController?action=login',
  },
  {
    id: 'alerta-licitacao',
    category: 'Outras buscas',
    title: 'Alerta Licitação',
    description: 'Licitações, contratos e compras públicas.',
    url: 'https://alertalicitacao.com.br/',
    searchUrl: (q) => g(`site:alertalicitacao.com.br ${q}`),
  },
  {
    id: 'portal-compras',
    category: 'Outras buscas',
    title: 'Portal de Compras Públicas',
    description: 'Processos de compras públicas.',
    url: 'https://www.portaldecompraspublicas.com.br/18/Processos/',
  },
  {
    id: 'transparencia',
    category: 'Outras buscas',
    title: 'Portal da Transparência',
    description: 'Gastos, contratos e servidores da União.',
    url: 'http://www.portaltransparencia.gov.br/',
    searchUrl: (q) => g(`site:portaltransparencia.gov.br ${q}`),
  },
];

export const OSINT_CATEGORIES = Array.from(new Set(OSINT_SOURCES.map((item) => item.category)));

export const BR_DOMAIN_CATEGORIES: Array<{ tld: string; description: string }> = [
  { tld: 'APP.BR', description: 'Aplicativos' },
  { tld: 'ART.BR', description: 'Artes: música, pintura, folclore' },
  { tld: 'COM.BR', description: 'Atividades comerciais' },
  { tld: 'DEV.BR', description: 'Desenvolvedores e plataformas' },
  { tld: 'ECO.BR', description: 'Atividades eco-ambientais' },
  { tld: 'EMP.BR', description: 'Pequenas e micro-empresas' },
  { tld: 'LOG.BR', description: 'Transportes e logística' },
  { tld: 'NET.BR', description: 'Atividades comerciais' },
  { tld: 'ONG.BR', description: 'Atividades não governamentais' },
  { tld: 'SEG.BR', description: 'Segurança' },
  { tld: 'TEC.BR', description: 'Tecnologia' },
  { tld: 'EDU.BR', description: 'Instituições de ensino superior' },
  { tld: 'BLOG.BR', description: 'Web logs' },
  { tld: 'NOM.BR', description: 'Pessoas físicas' },
  { tld: 'ADV.BR', description: 'Advogados' },
  { tld: 'MED.BR', description: 'Médicos' },
  { tld: 'ENG.BR', description: 'Engenheiros' },
  { tld: 'JOR.BR', description: 'Jornalistas' },
  { tld: 'GOV.BR', description: 'Instituições do governo federal' },
  { tld: 'JUS.BR', description: 'Instituições do Poder Judiciário' },
  { tld: 'ORG.BR', description: 'Instituições sem fins lucrativos' },
  { tld: 'MIL.BR', description: 'Forças Armadas' },
];
